version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "80:80"
    environment:
      - AWS_REGION=eu-north-1
      - AWS_DEFAULT_REGION=eu-north-1
      - S3_BUCKET=flask-app-static-store
      - DYNAMODB_TABLE=flask_app_metadata
    restart: always
